/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.awt.Dimension;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;

/**
 *
 * @author andre
 */
public class TelaAvisos extends javax.swing.JFrame {

    /**
     * Creates new form TelaAvisos
     */
    public TelaAvisos(int tipo) {
        super("Atenção");
        initComponents();
        imgUserSenha.setVisible(false);
        imgSenha.setVisible(false);
        imgDados.setVisible(false);
        imgServidor.setVisible(false);
        imgCadUser.setVisible(false);
        imgJaPossuiChave.setVisible(false);
        imgChavesNaoIguais.setVisible(false);
        imgChaveJaCad.setVisible(false);
        imgValorInvalido.setVisible(false);
        imgChaveNao.setVisible(false);
        imgContaNao.setVisible(false);
        imgCpfCad.setVisible(false);
        imgEmailCad.setVisible(false);
        imgTelefoneCad.setVisible(false);
        if(tipo == 1){
        imgUserSenha.setVisible(true);
        }
        if(tipo == 2){
        imgDados.setVisible(true);
        }
        if(tipo == 3){
        imgServidor.setVisible(true);
        }
        if(tipo == 4){
        imgCadUser.setVisible(true);
        }
        if(tipo == 5){        
        imgSenha.setVisible(true);        
        }
        if(tipo == 8){
        imgChaveJaCad.setVisible(true);
        }
        if(tipo == 10){
        imgChavesNaoIguais.setVisible(true);
        }
         if(tipo == 11){
        imgJaPossuiChave.setVisible(true);
        }
        if(tipo == 12){
        imgCadUser.setVisible(true);
        }
        if(tipo == 13){
        imgChaveNao.setVisible(true);
        }
        if(tipo == 14){
        imgContaNao.setVisible(true);
        }
        if(tipo == 15){
        imgCpfCad.setVisible(true);
        }
        if(tipo == 16){
        imgEmailCad.setVisible(true);
        }
        if(tipo == 17){
        imgTelefoneCad.setVisible(true);
        }
         
        
       
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

            addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e) {
                    dispose();
                }
            });    
        
    }

    public TelaAvisos() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgTelefoneCad = new javax.swing.JLabel();
        imgCpfCad = new javax.swing.JLabel();
        imgEmailCad = new javax.swing.JLabel();
        imgChaveNao = new javax.swing.JLabel();
        imgContaNao = new javax.swing.JLabel();
        imgValorInvalido = new javax.swing.JLabel();
        imgJaPossuiChave = new javax.swing.JLabel();
        imgChavesNaoIguais = new javax.swing.JLabel();
        imgChaveJaCad = new javax.swing.JLabel();
        imgCadUser = new javax.swing.JLabel();
        imgServidor = new javax.swing.JLabel();
        imgDados = new javax.swing.JLabel();
        imgSenha = new javax.swing.JLabel();
        imgUserSenha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgTelefoneCad.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/825423486012620863/1127114467667353683/Group_26_6.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgTelefoneCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        imgCpfCad.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/825423486012620863/1127114467344404562/Group_44_1.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgCpfCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        imgEmailCad.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/825423486012620863/1127114466899791882/Group_43_3.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgEmailCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        imgChaveNao.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/825423486012620863/1125183681682751650/Group_42.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgChaveNao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        imgContaNao.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/825423486012620863/1125183681426894858/Group_43.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgContaNao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        imgValorInvalido.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/825423486012620863/1125173736232976455/Group_41.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgValorInvalido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        imgJaPossuiChave.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/825423486012620863/1125173736656605315/Group_39_1.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgJaPossuiChave, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        imgChavesNaoIguais.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/825423486012620863/1125158021908148225/Group_38_1.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgChavesNaoIguais, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        imgChaveJaCad.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/825423486012620863/1125158022243696740/Group_37_1.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgChaveJaCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        imgCadUser.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/825423486012620863/1125137388256108725/Group_34.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgCadUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        imgServidor.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/825423486012620863/1125136239604019363/Group_33.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgServidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        imgDados.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/825423486012620863/1125135218383273994/Group_32.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        imgSenha.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/825423486012620863/1125133521602748556/Group_31_2.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        imgUserSenha.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/825423486012620863/1125110685723009135/Group_30_2.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgUserSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAvisos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAvisos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAvisos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAvisos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAvisos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgCadUser;
    private javax.swing.JLabel imgChaveJaCad;
    private javax.swing.JLabel imgChaveNao;
    private javax.swing.JLabel imgChavesNaoIguais;
    private javax.swing.JLabel imgContaNao;
    private javax.swing.JLabel imgCpfCad;
    private javax.swing.JLabel imgDados;
    private javax.swing.JLabel imgEmailCad;
    private javax.swing.JLabel imgJaPossuiChave;
    private javax.swing.JLabel imgSenha;
    private javax.swing.JLabel imgServidor;
    private javax.swing.JLabel imgTelefoneCad;
    private javax.swing.JLabel imgUserSenha;
    private javax.swing.JLabel imgValorInvalido;
    // End of variables declaration//GEN-END:variables
}
